on:
  push:
    paths:
      - 'go/**'

jobs:
  test-go:
    runs-on: ubuntu-latest
    env:
      working-directory: "go"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version:  1.16.2
      - run: ./run_test.sh
        working-directory: ${{env.working-direcrory}}
