name: test-rust
on:
  push:
    paths:
      - 'rust/**'
      - '.github/workflows/test-rust.yml'

jobs:
  test-rust:
    runs-on: ubuntu-latest
    env:
      working-directory: "rust"
    steps:
      - uses: actions/checkout@v2
      - run: |
          directories=$(find "." -type d -not -path "." -maxdepth 1)
          for d in ${directories}; do
            cd $d
            cargo test -- --ignored
            cd ..
          done
        working-directory: ${{env.working-directory}}
