on: push

jobs:
  test-elixir:
    runs-on: ubuntu-latest
    env:
      working-directory: "elixir"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.2
          elixir-version: 1.10.2
      - run: |
          directories=$(find "." -type d -not -path ".")
          for d in ${directories}; do
            if [ -f ${d}/mix.exs ]; then
              mix deps.get
              mix test
            else
              elixir ${d}/*_test.exs
            fi
          done
        working-directory: ${{env.working-directory}}
