name: test-go
on:
  push:
    paths:
      - 'go/**'
      - '.github/workflows/test-go.yml'

jobs:
  test-go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
      - uses: actions/checkout@v4
      - run: ./run_test.sh
