name: test-elixir
on:
  push:
    paths:
      - 'elixir/**'
      - '.github/workflows/test-elixir.yml'

jobs:
  test-elixir:
    runs-on: ubuntu-latest
    env:
      working-directory: "elixir"
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 28
          elixir-version: 1.18
      - run: |
          directories=$(find "." -type d -not -path "." -maxdepth 1)
          for d in ${directories}; do
            if [ -f ${d}/mix.exs ]; then
              cd $d
              mix deps.get
              mix test
              cd ..
            else
              elixir ${d}/*_test.exs
            fi
          done
        working-directory: ${{env.working-directory}}
